# Generated by Django 2.1.7 on 2019-03-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='key',
            field=models.CharField(default='some strings', max_length=500),
        ),
    ]
