# Generated by Django 2.1.7 on 2019-03-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20190301_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ciphertext',
            field=models.TextField(default='some strings'),
        ),
        migrations.AddField(
            model_name='post',
            name='plaintext',
            field=models.TextField(default='some strings'),
        ),
    ]
