# Generated by Django 2.1.7 on 2019-03-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20190302_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='decrypted',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='ciphertext',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='key',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='plaintext',
            field=models.TextField(default=''),
        ),
    ]
