# Generated by Django 2.1.7 on 2019-03-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
    ]
