# Generated by Django 2.1.7 on 2019-03-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_remove_comments_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('daVinciPrivKey', models.TextField()),
                ('daVinciPubKey', models.TextField()),
                ('bobRossPrivKey', models.TextField()),
                ('bobRossPubKey', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
